server:
  port: 8091

spring:
  cloud:
    stream:
      instance-count: 2
      instance-index: 1
      function:
        definition: orderStoreProcess;verifiedOrderProcess;orderCountByUserIdProcess  # active 3 processes of kafka stream
      kafka:
        binder:
          configuration:
            commit.interval.ms: 100
            default:
              key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              value.serde: org.apache.kafka.common.serialization.Serdes$JsonSerde
          brokers: 10.218.188.198:9092
          autoAddPartitions: true
          minPartitionCount: 4
          replicationFactor: 1
        streams:
          binder:
            configuration:
              application.server: localhost:8091
            functions:
              #            #APPLICATION ID if we have multi stream app within the same springboot app
              orderCountByUserIdProcess:
                applicationId: order-count-by-user-id-instance
              orderStoreProcess:
                applicationId: order-store-process-id-instance
              verifiedOrderProcess:
                applicationId: verified-order-process-id-instance
            state-store-retry:
              max-attempts: 3
              backoff-period: 2000
      bindings:
        rest-order-out:
          destination: microservice-orders
          contentType: application/json
#          nativeDecoding: true
#          consumer:
#            keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
#            valueSerde: org.apache.kafka.common.serialization.Serdes$JsonSerde
#        orderCountByUserId-in-0:
#          destination: microservice-orders
#          contentType: application/json
        orderStoreProcess-in-0:
          destination: microservice-orders
          contentType: application/json
        orderCountByUserIdProcess-in-0:
          destination: microservice-orders
          contentType: application/json
        verifiedOrderProcess-in-0:
          destination: microservice-verified-orders
          contentType: application/json
        verifiedOrderProcess-in-1:
          destination: microservice-verified-customer
          contentType: application/json
        verifiedOrderProcess-out-0:
          destination: microservice-completed-orders
          contentType: application/json
          producer:
            keySerde: org.apache.kafka.common.serialization.Serdes$LongSerde
            valueSerde: org.apache.kafka.common.serialization.Serdes$JsonSerde





